site_name: AppsDock OS Documentation
site_url: https://appsdock.github.io/docs/
copyright: © 2021 AppsDock GbR
repo_url: https://github.com/appsdock/docs
repo_name: GitHub

docs_dir: src
site_dir: docs

theme:
  name: material
  palette:
    primary: green
    accent: light green

markdown_extensions:
  - admonition
  - codehilite

nav:
  - Introduction: index.md
  - Getting Started:
    - Guidelines:
      - Version Control: gettingstarted/guidelines/version-control.md
    - XDebug: gettingstarted/xdebug.md
    - API:
      - REST: gettingstarted/api/rest.md
  - Identity and Access:
    - Authentication: identity-access/authentication.md
    - Identity: identity-access/identity.md
    - Policy: identity-access/policies.md
