site_name: AppsDock OS Documentation
site_url: https://appsdock.github.io/docs/
copyright: © 2021 AppsDock GbR
repo_url: https://github.com/appsdock/docs
repo_name: GitHub

docs_dir: src
site_dir: docs

theme:
  name: material
  palette:
    primary: green
    accent: light green

extra_css:
  - assets/css/appsdock.css
extra:
  manifest: manifest.webmanifest

markdown_extensions:
    # Enable abbreviations
  - abbr
    # Enable admonitions
  - admonition
    # Enable footnotes
  - footnotes
    # Enable syntax highlighting for code blocks
  - pymdownx.highlight:
      # Show line numbers for code blocks
      linenums: true
    # Enable syntax highlighting for inline code
  - pymdownx.inlinehilite
    # Allows for the nesting of code blocks inside other blocks (recommended)
  - pymdownx.superfences

nav:
  - Introduction: index.md
  - Getting Started:
    - API:
      - REST: gettingstarted/api/rest.md
    - Guidelines:
      - Commit messages: gettingstarted/guidelines/commit-messages.md
      - Configuration: gettingstarted/guidelines/configuration.md
      - Exceptions:
        - Error codes: gettingstarted/guidelines/exceptions/error-codes.md
        - Runtime:
          - Illegal argument: gettingstarted/guidelines/exceptions/runtime/illegal-argument.md
          - Illegal format: gettingstarted/guidelines/exceptions/runtime/illegal-format.md
          - Illegal type: gettingstarted/guidelines/exceptions/runtime/illegal-type.md
      - Naming convention: gettingstarted/guidelines/naming-convention.md
    - PhpStorm:
      - Xdebug: gettingstarted/phpstorm/xdebug.md
  - Identity and access:
    - Authentication: identity-access/authentication.md
    - Identity: identity-access/identity.md
    - Policies and permissions: identity-access/policies-and-permissions.md
