site_name: 'AppsDock Application Server'
site_url: 'https://appsdock.github.io/docs/'
copyright: 'Copyright &copy; 2020 AppsDock Enterprise'
repo_url: https://github.com/appsdock/docs
repo_name: GitHub

docs_dir: src
site_dir: docs

theme:
  feature:
    #tabs: true
  name: 'material'
  palette:
    primary: 'blue grey'
    accent: 'teal'

extra_css:
  - 'custom.css'

markdown_extensions:
  - admonition
  - codehilite
  #- pymdownx.tabbed

nav:

  - Introduction: index.md
  - Guidelines:
    - Version Control: guidelines/version-control.md
  - Getting Started:
    - Introduction: gettingstarted/introduction.md
    - Environment: gettingstarted/environment.md
    - Setup: gettingstarted/setup.md
    - XDebug: gettingstarted/xdebug.md
  - Identity and Access:
      - Introduction: identity-access/intro.md
      - Authentication: identity-access/authentication.md
      - Authorization: identity-access/authorization.md
      - Identity: identity-access/identity.md
      - Policy: identity-access/policies.md
  - Dev-Process:
    - Introduction: process/introduction.md
    - Code Generation: process/generation.md
  - Architecture:
    - Backend:
      - Introduction: architecture/backend/introduction.md
  - Apps:
    - Introduction: apps/introduction.md
  - API:
    - Rest: API/REST.md
