site_name: AppsDock OS Documentation
site_url: https://appsdock.github.io/docs/
copyright: © 2021 AppsDock GbR
repo_url: https://github.com/appsdock/docs
repo_name: GitHub

docs_dir: src
site_dir: docs

theme:
  name: material
  features:
      # Enable XHR loading
    - navigation.instant
      # Enable sections
    - navigation.sections
      # Enable tabs
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes
  palette:
    scheme: slate
    primary: green
    accent: light green

extra_css:
  - assets/css/appsdock.css
extra:
  manifest: manifest.webmanifest

markdown_extensions:
    # Enable abbreviations
  - abbr
    # Enable admonitions
  - admonition
    # Enable footnotes
  - footnotes
    # Enable syntax highlighting for code blocks
  - pymdownx.highlight:
      # Show line numbers for code blocks
      linenums: true
    # Enable syntax highlighting for inline code
  - pymdownx.inlinehilite
    # Allows for the nesting of code blocks inside other blocks (recommended)
  - pymdownx.superfences
    # Table of contents
  - toc:
      # Limit the displayed levels
      toc_depth: 4

nav:
  - Home: index.md
  - Concepts:
      - Introduction: concepts/introduction.md
      - Configuration: concepts/configuration.md
      - Infrastructure:
        - Message Queue (AMQP): concepts/infrastructure/amqp.md
      - Identity and access:
        - Authentication: concepts/identity-access/authentication.md
        - Identity: concepts/identity-access/identity.md
        - Policies and permissions: concepts/identity-access/policies-and-permissions.md
  - Getting Started:
    - Environment: gettingstarted/environment/index.md
      - IDE: gettingstarted/environment/ide.md
      - Version Control: gettingstarted/environment/version-control.md
    - Guidelines:
      - Exception errors: gettingstarted/guidelines/exception-errors.md
      - Naming convention: gettingstarted/guidelines/naming-convention.md
      - REST API: gettingstarted/guidelines/rest-api.md
    - Application:
      - Structure: gettingstarted/application/structure.md
  - API Reference:
    - Introduction: api/index.md
    - Authentication: api/authentication.md
    - Errors: api/errors.md
    - Pagination: api/pagination.md
    - Resources:
      - Access: api/rest/access.md
      - App: api/rest/app.md
      - Configuration: api/rest/configuration.md
      - Identity: api/rest/identity.md
      - Mail: api/rest/mail.md
      - Organization: api/rest/organization.md
      - Status: api/rest/status.md
  - Troubleshooting:
    - Core: exception-errors/core.md
    - System: exception-errors/system.md
    - Integration: exception-errors/integration.md
    - Plugin: exception-errors/plugin.md
    - App: exception-errors/app.md

