site_name: AppsDock OS Documentation
site_url: https://appsdock.github.io/docs/
copyright: © 2021 AppsDock GbR
repo_url: https://github.com/appsdock/docs
repo_name: GitHub

docs_dir: src
site_dir: docs

theme:
  name: material
  features:
      # Enable XHR loading
    - navigation.instant
      # Enable sections
    - navigation.sections
      # Enable tabs
    - navigation.tabs
    - navigation.top
  palette:
    scheme: slate
    primary: green
    accent: light green

extra_css:
  - assets/css/appsdock.css
extra:
  manifest: manifest.webmanifest

markdown_extensions:
    # Enable abbreviations
  - abbr
    # Enable admonitions
  - admonition
    # Enable footnotes
  - footnotes
    # Enable syntax highlighting for code blocks
  - pymdownx.highlight:
      # Show line numbers for code blocks
      linenums: true
    # Enable syntax highlighting for inline code
  - pymdownx.inlinehilite
    # Allows for the nesting of code blocks inside other blocks (recommended)
  - pymdownx.superfences
    # Table of contents
  - toc:
      # Limit the displayed levels
      toc_depth: 3

nav:
  - Home: index.md
  - Getting Started:
    - Guidelines:
      - Commit messages: gettingstarted/guidelines/commit-messages.md
      - Configuration: gettingstarted/guidelines/configuration.md
      - Exception errors: gettingstarted/guidelines/exception-errors.md
      - Naming convention: gettingstarted/guidelines/naming-convention.md
      - REST API: gettingstarted/guidelines/rest-api.md
    - PhpStorm:
      - Xdebug: gettingstarted/phpstorm/xdebug.md
  - API:
    - REST:
      - Access: api/rest/access.md
      - App: api/rest/app.md
      - Configuration: api/rest/configuration.md
      - Identity: api/rest/identity.md
      - Mail: api/rest/mail.md
      - Organization: api/rest/organization.md
  - Exception errors:
    - Core: exception-errors/core.md
    - System: exception-errors/system.md
    - Integration: exception-errors/integration.md
    - Plugin: exception-errors/plugin.md
    - App: exception-errors/app.md
  - Identity and access:
    - Authentication: identity-access/authentication.md
    - Identity: identity-access/identity.md
    - Policies and permissions: identity-access/policies-and-permissions.md
