name: Build

on: push

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Generate website
        run: docker run --rm -v ${PWD}:/docs/ squidfunk/mkdocs-material build

      - name: Commit and push
        run: |
          git config --global user.name '${{ secrets.GIT_USER }}'
          git config --global user.email '${{ secrets.GIT_EMAIL }}'
          git add *
          git commit -am 'CHANGE #automated #documentation Documentation generated'
          git push
