name: Build

on: push

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Generate documentation
        run: docker run --rm -v ${PWD}:/docs/ squidfunk/mkdocs-material build

      - name: Wait for Docker
        run: sleep 10

      - name: Commit and push documentation
        run: |
          git config --global user.name 'Automated Build'
          git config --global user.email 'github@appsdock.de'
          git add *
          git commit -am 'CHANGE #documentation #automatedBuild Automated build'
          git push
