name: Build

on: push

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Generate website
        run: docker run --rm -v ${PWD}:/docs/ squidfunk/mkdocs-material build

      - name: Add custom domain
        run: echo "docs.appsdock.de" > ./docs/CNAME

      # To prevent error code 1 if nothing to commit wrap git commands into an echo (simple solution)
      - name: Commit and push
        run: |
          git config --global user.name '${{ secrets.GIT_USER }}'
          git config --global user.email '${{ secrets.GIT_EMAIL }}'
          echo `git add -A && git commit -am 'CHANGE #automated #documentation Documentation generated' && git push`
